language: elixir
env:
  - MIX_ENV=test
matrix:
  include:
    - elixir: 1.6
      otp_release: 20.0
    - elixir: 1.7
      opt_release: 20.0
    - elixir: 1.8
      otp_release: 21.0
script:
  - mix deps.compile
  - mix format --check-formatted --dry-run
  - mix test
  - mix coveralls.travis
after_script:
  - mix credo
